#!/bin/bash

# Coolify Deployment Helper Script
# This script helps prepare your backend for Coolify deployment

echo "🚀 Pickplace Backend - Coolify Deployment Helper"
echo "================================================"

# Check if required files exist
echo "📋 Checking deployment files..."

if [ ! -f "Dockerfile" ]; then
    echo "❌ Dockerfile not found!"
    exit 1
else
    echo "✅ Dockerfile found"
fi

if [ ! -f "docker-compose.yml" ]; then
    echo "❌ docker-compose.yml not found!"
    exit 1
else
    echo "✅ docker-compose.yml found"
fi

if [ ! -f "env.example" ]; then
    echo "❌ env.example not found!"
    exit 1
else
    echo "✅ env.example found"
fi

if [ ! -f ".dockerignore" ]; then
    echo "❌ .dockerignore not found!"
    exit 1
else
    echo "✅ .dockerignore found"
fi

# Test Docker build locally (optional)
echo ""
echo "🔨 Testing Docker build locally..."
read -p "Do you want to test the Docker build locally? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Building Docker image..."
    docker build -t pickplace-backend-test .
    
    if [ $? -eq 0 ]; then
        echo "✅ Docker build successful!"
        echo "🧪 You can test the container with:"
        echo "   docker run -p 5000:5000 --env-file .env pickplace-backend-test"
    else
        echo "❌ Docker build failed!"
        exit 1
    fi
fi

# Environment variables check
echo ""
echo "🔧 Environment Variables Checklist:"
echo "Please ensure you have configured these in Coolify:"
echo ""
echo "Required:"
echo "  - NODE_ENV=production"
echo "  - PORT=5000"
echo "  - MONGODB_URI"
echo "  - JWT_SECRET"
echo "  - FRONTEND_URL"
echo ""
echo "Optional but recommended:"
echo "  - ADMIN_EMAIL & ADMIN_PASSWORD"
echo "  - CLOUDINARY_* (for file uploads)"
echo "  - GMAIL_* & GOOGLE_* (for emails)"
echo "  - SSLCOMMERZ_* (for payments)"
echo ""

# Pre-deployment checklist
echo "📝 Pre-deployment Checklist:"
echo ""
echo "Backend Setup:"
echo "  [ ] All environment variables configured in Coolify"
echo "  [ ] MongoDB database accessible from Coolify server"
echo "  [ ] Domain/subdomain configured for backend"
echo "  [ ] SSL certificate will be auto-generated by Coolify"
echo ""
echo "External Services:"
echo "  [ ] Cloudinary account setup (if using file uploads)"
echo "  [ ] Gmail OAuth configured (if using email features)"
echo "  [ ] SSLCommerz account setup (if using payments)"
echo ""
echo "Coolify Configuration:"
echo "  [ ] Git repository connected"
echo "  [ ] Build settings: Dockerfile path = backend/Dockerfile"
echo "  [ ] Docker context = backend/"
echo "  [ ] Port = 5000"
echo "  [ ] Health check = /api/health"
echo ""

echo "🎯 Next Steps:"
echo "1. Commit and push all changes to your Git repository"
echo "2. Go to your Coolify dashboard"
echo "3. Create a new application from Git repository"
echo "4. Configure environment variables"
echo "5. Set up domain and SSL"
echo "6. Deploy!"
echo ""
echo "📖 For detailed instructions, see: COOLIFY_DEPLOYMENT_GUIDE.md"
echo ""
echo "✨ Good luck with your deployment!"
